language: python
sudo: false
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libtool
      - libncurses-dev
      - libgpm-dev
      - ccache
cache:
  - ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
script:
  - ./bootstrap.sh
  - CXXFLAGS="-Wall" LDFLAGS="-Wl,--as-needed" ./configure
  - make
